owner: foxpress-design
repo: status

sites:
  - name: foxpress.cloud
    url: https://foxpress.cloud
  - name: Server
    url: 51.79.99.22
    port: 443
    check: "tcp-ping"
  - name: cPanel
    url: https://51.79.99.22:2083
    expectedStatusCodes:
      - 200
      - 301
      - 302
      - 401
  - name: Email (SMTP)
    url: 51.79.99.22
    port: 25
    check: "tcp-ping"

status-website:
  publish: true
  cname: status.foxpress.cloud
  name: "foxpress.cloud Status"
  logoUrl: ""
  theme: dark
  navbar:
    - title: Status
      href: /
    - title: foxpress.cloud
      href: https://foxpress.cloud

notifications:
  - type: ntfy
    url: https://ntfy.sh/foxpress-alerts

commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
  statusChange: ":construction: $SITE is $STATUS [upptime]"
  newIssue: ":bug: $SITE is down [upptime]"
  closeIssue: ":white_check_mark: $SITE is back up [upptime]"
  graphs: ":bento: Update graphs [upptime]"
  responseTime: ":zap: Update response time graphs [upptime]"
